### ISSUE TITLE
Cross-platform file name handling in .NET Core

### ISSUE THREAD

**Issue by Toetje585** [ProjectCeleste/Celeste.GameScan#1]
Windows using Backslash. Linux  is using slash causing the GameScanner to detect and write files wrong for example a downloaded file will look like this on linux:

art\Art.bar instead of placing it in the /art folder it will write the file as a full file ''art\art.bar'

**Comment by Toetje585** [comment]
Wanted to add that Linux is also sensitive to upper and lower case naming :)

**Comment by martinmine** [comment]
I believe this was fixed as part of 1a7e6dfa1a29fe830506c946aac4d62ecdca593c, let me know if I am wrong and I will re-open this issue and look more into this.
